services:
  certs:
    image: alpine:3.19
    entrypoint: ["/bin/sh", "/scripts/bootstrap.sh"]
    env_file:
      - .env.example
    volumes:
      - traefik-certs:/certs
      - ./docker/certs:/scripts:ro

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: smtp_oauth2
      POSTGRES_USER: smtp
      POSTGRES_PASSWORD: smtp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - internal

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file:
      - .env.example
    environment:
      DATABASE_URL: postgresql://smtp:smtp@postgres:5432/smtp_oauth2?schema=public
      REDIS_URL: redis://redis:6379
    volumes:
      - traefik-certs:/certs:ro
    depends_on:
      - postgres
      - redis
    networks:
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=PathPrefix(`/api`)
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.routers.api.service=api
      - traefik.http.services.api.loadbalancer.server.port=3000

  smtp:
    build:
      context: .
      dockerfile: apps/smtp/Dockerfile
    env_file:
      - .env.example
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    networks:
      - internal
    ports:
      - '2525:2525'
    volumes:
      - traefik-certs:/certs:ro

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    env_file:
      - .env.example
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://smtp:smtp@postgres:5432/smtp_oauth2?schema=public
    depends_on:
      - api
      - redis
    networks:
      - internal

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    env_file:
      - .env.example
    depends_on:
      - api
    networks:
      - internal
      - public
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=PathPrefix(`/`)
      - traefik.http.routers.web.entrypoints=web
      - traefik.http.routers.web.service=web
      - traefik.http.services.web.loadbalancer.server.port=3000

  traefik:
    image: traefik:v2.11
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - traefik-certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - public
      - internal
    depends_on:
      - certs
      - web
      - api

networks:
  internal:
    driver: bridge
  public:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  traefik-certs:
